### ISSUE TITLE
数据api是怎么获取的？

### ISSUE THREAD

**Issue by deepred5** [smallpath/psnine#2]
比如首页http://psnine.com/ 的列表数据好像不是通过接口返回的，请问用react-native是怎么获取这些数据的？

**Comment by deepred5** [comment]
看了下，应该用的是`cheerio-without-node-native`_(:3」∠)_

**Comment by smallpath** [comment]
深红下午好, api是用[cheerio](https://github.com/cheeriojs/cheerio)爬取的, 解析代码之前在这个仓库, 不过发现[psnine被vgtime爬数据](http://psnine.com/gene/19672)后我把它放到私有仓库里了

**Comment by smallpath** [comment]
@deepred5  (:3」∠) 是的, react-native不能直接跑node代码, 得转一下
