### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by wuyunqiang** [smallpath/psnine#4]
git clone https://github.com/smallpath/psnine.git
cd psnine
npm install --registry=https://registry.npm.taobao.org
下载 psnine-patcher , 并将其中所有内容全部拷贝至node_modules
react-naitve run-andorid 运行不起来.

**Comment by smallpath** [comment]
这并不是npm install就能跑起来的项目，在安卓上要求不少SDK Platform，文档里有写
> 前置: Android Studio, SDK Platform 23 ~ 26, SDK Build-Tools 23.0.1、23.0.3、25.0.0、25.0.2、26.0.0、26.0.1
