### ISSUE TITLE
奖杯tips无法加载

### ISSUE THREAD

**Issue by docps4** [smallpath/psnine#5]
每次都只能加载第一条

**Comment by smallpath** [comment]
IOS？安卓的没问题，下次更新会修复

**Comment by docps4** [comment]
是安卓版本，tips只能加载出来第一条，系统是8.0

**Comment by smallpath** [comment]
哦哦，应该是安卓8.0的问题，

**Comment by smallpath** [comment]
是只有奖杯tips显示第一条？还是说所有有评论的页面只显示第一条？如果是后者，那么你是没有登录或者登录状态过期了，拉出左侧抽屉长按头像退出重新登录即可。如果是前者的话给一下安卓机器型号与你的psnid，方便我复现

**Comment by docps4** [comment]
是后者，我之前以为不登录也能看评论

**Comment by docps4** [comment]
确实奖杯tips只显示第一条，机器是nexus6p，psnid我没有认证

**Comment by smallpath** [comment]
这个必须认证后登陆，否则网页上没有回复的id，显示不出来就是可预期的了

**Comment by docps4** [comment]
通过认证之后tips显示正常

smallpath <notifications@github.com> 于 2017年11月14日周二 10:56写道：

**Comment by smallpath** [comment]
其实之前不登录也会显示的，大概两月前网站改版把回复里的id全给删了，只在`点赞``回复`这种按钮上有id，因此现在不登录确实是看不到的
